---
# Usage
#
# Run the pre-commit hooks on all files using:
#
#     $ pre-commit run --all-files
#
# Update this file:
#     $ pre-commit autoupdate; pre-commit install
#
# Install the pre-commit hook using:
#
#     $ pre-commit install
#
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: check-ast
          - id: check-byte-order-marker
          - id: check-case-conflict
          - id: check-docstring-first
          - id: check-executables-have-shebangs
          - id: check-json
          - id: check-yaml
          - id: debug-statements
          - id: detect-aws-credentials
            args: [--allow-missing-credentials]
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: mixed-line-ending
          - id: check-added-large-files
            args: [--maxkb=10000]
          - id: check-merge-conflict
          - id: check-symlinks
          - id: pretty-format-json
            args: [--autofix, --indent=2, --no-sort-keys]
          - id: requirements-txt-fixer
    - repo: https://github.com/timothycrosley/isort
      rev: 5.13.2
      hooks:
          - id: isort
            args: [--profile, black]
    - repo: https://github.com/psf/black
      rev: 24.8.0
      hooks:
          - id: black
            args:
                - --line-length=120
            language_version: python3
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt
    - repo: https://github.com/PyCQA/flake8
      rev: 7.1.1
      hooks:
          - id: flake8
            args: [--max-line-length=120, --ignore=E203]
            exclude: ^lean_universe/utils/params.py
            additional_dependencies:
                - flake8-bugbear
                - flake8-comprehensions
                - flake8-simplify
    - repo: https://github.com/asottile/yesqa
      rev: v1.5.0
      hooks:
          - id: yesqa
            additional_dependencies:
                - flake8-bugbear
                - flake8-comprehensions
                - flake8-docstrings
    - repo: https://github.com/nametake/pre-commit-prototool
      rev: v0.1.0
      hooks:
          - id: prototool-lint
          - id: prototool-format-fix
    - repo: https://github.com/BlankSpruce/gersemi
      rev: 0.15.1
      hooks:
          - id: gersemi  # CMake formatter
    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.10.0.1
      hooks:
          - id: shellcheck
    - repo: https://github.com/commitizen-tools/commitizen
      rev: v3.29.0
      hooks:
          - id: commitizen
          - id: commitizen-branch
            stages: [push]
    - repo: https://github.com/hadialqattan/pycln
      rev: v2.4.0
      hooks:
          - id: pycln
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.17.0
      hooks:
          - id: pyupgrade
            args: [--py39-plus, --keep-runtime-typing]
    - repo: https://github.com/asottile/blacken-docs
      rev: 1.18.0
      hooks:
          - id: blacken-docs
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.11.2
      hooks:
          - id: mypy
            #verbose: true
            args: [--ignore-missing-imports, --explicit-package-bases, --show-error-codes]
            additional_dependencies: [types-requests]
    - repo: https://github.com/PyCQA/bandit
      rev: 1.7.9
      hooks:
          - id: bandit
            exclude: ^lean_universe/utils/params.py
