---
name: Run precommit
on:
    pull_request:
    workflow_dispatch:
jobs:
    pre_commit_check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.1.1
            - uses: actions/setup-python@v5.0.0
              with:
                  python-version: '3.10'
            - name: Install pre-commit
              run: pip install pre-commit
            - name: Run pre-commit testing
              run: pre-commit run --all-files
